### PR TITLE
Add noUnusedLocals to tsconfig to improve type checks.

### PR DESCRIPTION
**Pull request by PeterEnevoldsen**
Update relevant import to support noUnusedLocals.

### CODE REVIEW

**Comment by fknop** [comment]
It looks like something is wrong with ngc, I'll relaunch the CI tests.

**Comment by PeterEnevoldsen** [comment]
I also had problems with that locally even with the untouched master branch. It appeared when running npm install.

**Comment by fknop** [comment]
It's probably coming from this PR, I had another yesterday and it went fine

**Comment by fknop** [comment]
It looks like there is a breaking change with ngc... I don't have time to look at it this week end, so it'll we next week.

**Comment by fknop** [comment]
Ok, I actually found it. It's coming from Typescript 2.1 not working with ngc. I fixed the version of typescript to 2.0.8.

**Pull request merged**
