### PR TITLE
Fix tenth ordinal

### LINKED ISSUE #83: Incorrect Ordinals
**I'm submitting a ...**  (check one with "x")

```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

Ordinals from 11 to 13 are not correct (11st, 12nd, 13rd)

**Expected behavior**

They should be 11th, 12th, 13th
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

### PR DESCRIPTION
**Pull request by christopheelkhoury**
Closes #83 

**Changes Proposed in this Pull Request:**
- Add test cases in `ordinal.pipe.spec.ts` to validate any number ending with 11, 12 or 13 will be transformed to 11th, 12th and 13th instead of 11st, 12nd and 13rd respectively.
- Add function in `ordinal.pipe.ts` to validate the last two digits of a received number and return the transform accordingly.

### CODE REVIEW

**Comment by fknop** [comment]
CI seems to fail with node 7. This is because of new versions of angular not supporting it.

**Comment by fknop** [comment]
I changed the travis config: https://github.com/fknop/angular-pipes/commit/549d277837e0f109e56abafab64c886a4dc0fed8,

if it pass, you can pull it in your own branch

**Comment by christopheelkhoury** [comment]
@fknop what do you need me to do then?

**Comment by fknop** [comment]
You can pull master and repush to your branch to restart the travis jobs with the good configuration

**Comment by tanayv** [comment]
@fknop Apologies for not addressing this during my first implementation of the Ordinal pipe. 

@christopheelkhoury Are you still working on this, or can I give it a try?

**Comment by christopheelkhoury** [comment]
@tanayv can you push onto the same branch?

**Comment by tanayv** [comment]
@christopheelkhoury I'm not sure: I will probably have to make commits to the fix-tenth-ordinal branch on your fork of this repository for them to show up in this PR. 

If that is ok with you, I can make a PR to merge into the ``christopheelkhoury:fix-tenth-ordinal`` branch with my fixes and once you accept my PR in your fork the changes should update in this pull request on ``fknop/angular-pipes`` also.

**Pull request merged**
