### PR TITLE
- Add pipe slugfy to url friendly

### PR DESCRIPTION
**Pull request by Iraecio**
Function to generate links with friendly url style

### CODE REVIEW

**Comment by fknop** [comment]
Thanks,

Can you please also add documentation ?

**Comment by Iraecio** [comment]
Yes moment

**Comment by fknop** [comment]
One more thing, I'm not a native english speaker but I believe it should be **slugify** instead of **slugfy**

**Comment by fknop** [comment]
Published in [5.2.0](https://github.com/fknop/angular-pipes/blob/master/CHANGELOG.md#520).

**Pull request merged**
